// <auto-generated />
using System;
using CreeGuanajuato.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CreeGuanajuato.Migrations
{
    [DbContext(typeof(CreeGuanajuatoContext))]
    partial class CreeGuanajuatoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CreeGuanajuato.Models.Colonia", b =>
                {
                    b.Property<int>("id_colonia")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("codigo_postal");

                    b.Property<string>("cve_loc")
                        .IsRequired();

                    b.Property<int?>("id_municipio")
                        .IsRequired();

                    b.Property<string>("nombre_colonia")
                        .IsRequired();

                    b.HasKey("id_colonia");

                    b.HasIndex("id_municipio");

                    b.ToTable("Colonia");
                });

            modelBuilder.Entity("CreeGuanajuato.Models.Direccion", b =>
                {
                    b.Property<int>("id_direccion")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("calle");

                    b.Property<int?>("id_colonia")
                        .IsRequired();

                    b.Property<string>("numero");

                    b.HasKey("id_direccion");

                    b.HasIndex("id_colonia");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("CreeGuanajuato.Models.Escolaridad", b =>
                {
                    b.Property<int>("id_escolaridad")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .IsRequired();

                    b.HasKey("id_escolaridad");

                    b.ToTable("Escolaridad");
                });

            modelBuilder.Entity("CreeGuanajuato.Models.Estado", b =>
                {
                    b.Property<int>("id_estado")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cve_agee")
                        .IsRequired();

                    b.Property<string>("nombre_estado")
                        .IsRequired();

                    b.HasKey("id_estado");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("CreeGuanajuato.Models.EstadoCivil", b =>
                {
                    b.Property<int>("id_estado_civil")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .IsRequired();

                    b.HasKey("id_estado_civil");

                    b.ToTable("EstadoCivil");
                });

            modelBuilder.Entity("CreeGuanajuato.Models.Municipio", b =>
                {
                    b.Property<int>("id_municipio")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cve_agem");

                    b.Property<int?>("id_estado")
                        .IsRequired();

                    b.Property<string>("nombre_municipio")
                        .IsRequired();

                    b.HasKey("id_municipio");

                    b.HasIndex("id_estado");

                    b.ToTable("Municipio");
                });

            modelBuilder.Entity("CreeGuanajuato.Models.Necesidad", b =>
                {
                    b.Property<int>("id_necesidad")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .IsRequired();

                    b.HasKey("id_necesidad");

                    b.ToTable("Necesidad");
                });

            modelBuilder.Entity("CreeGuanajuato.Models.Colonia", b =>
                {
                    b.HasOne("CreeGuanajuato.Models.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("id_municipio")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CreeGuanajuato.Models.Direccion", b =>
                {
                    b.HasOne("CreeGuanajuato.Models.Colonia", "Colonia")
                        .WithMany()
                        .HasForeignKey("id_colonia")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CreeGuanajuato.Models.Municipio", b =>
                {
                    b.HasOne("CreeGuanajuato.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
